---
title: "cais-expr"
author: "Hanon McShea"
date: "2024-09-09"
output: html_document
---

```{r setup, include=FALSE}
library("tidyverse")
library("Biostrings")
library("seqinr")
library("ggplot2")
library("scales")

knitr::opts_knit$set(root.dir = "C:/Users/hanon/Documents/GitHub/aa_flux/cais/cais-expr")
getwd()

mytheme <- theme(axis.title=element_text(size=16, face="bold"), axis.text=element_text(size=14), panel.background = element_rect(fill = "white", colour = "grey50"), panel.grid.major = element_line(colour = "grey90"), panel.grid.minor = element_blank(), panel.border = element_rect(color = "grey50", fill=NA), plot.margin = unit(c(0.4, 0.4, 0.1, 0.1), "cm"))
```

``` {r read-data}
genes <- readDNAStringSet("mouse_genes_100codons.fasta")
headers <- names(genes)
sequences <- as.character(genes)
ENSMUSP <- sapply(strsplit(headers, "\\|"), function(x) x[3])

mousedf <- data.frame(ENSMUSP = ENSMUSP, Sequence = sequences, stringsAsFactors = FALSE)

expression_data <- read.table("mouse_expr.txt", header = FALSE, skip = 12, stringsAsFactors = FALSE)
colnames(expression_data) <- c("ENSMUSP_full", "expr")
expression_data$ENSMUSP <- sapply(strsplit(expression_data$ENSMUSP_full, "\\."), function(x) x[2])

# Merge the dataframes based on the ENSMUSP column
mousedf <- merge(mousedf, expression_data[, c("ENSMUSP", "expr")], by = "ENSMUSP", all.x = TRUE)
mousedf <- mousedf %>% drop_na()

mousedf2 <- arrange(mousedf, expr)
mousedf2

#tooshort <- 300 
#longgenes <- genes[width(genes) >= tooshort]
# write a new file with the subset
#writeXStringSet(longgenes,'mouse_genes_100codons.fasta',format='fasta')
```


``` {r binsplits}
split_dfs <- split(mousedf2, cut(seq(1, nrow(mousedf2)), breaks = 10, labels = FALSE))

for (i in seq_along(split_dfs)) {
    # Create a filename for each split
    filename <- paste0("mouse-expr_", i, ".csv")
    
    # Write the dataframe to a CSV file
    write.csv(split_dfs[[i]], filename, quote=F, row.names=F)
}

for (i in seq_along(split_dfs)) {
    # Create a filename for each split
    filename <- paste0("mouse-expr_", i, ".fasta")
    
    # Write the dataframe to a CSV file
    write.csv(paste(split_dfs[[i]]$Sequence, collapse=""), filename, quote=F, row.names=F)
}

write.csv(mousedf2, file="mouse-genes-expr.csv", quote=F, row.names=F)
```

``` {r GC of bins}
bins <- readDNAStringSet("mouse-expr-bins-concat.fasta")
letterFrequency(bins$bin1, letters="GC", as.prob=T) #0.4977083 
letterFrequency(bins$bin2, letters="GC", as.prob=T) #0.5083575 
letterFrequency(bins$bin3, letters="GC", as.prob=T) #0.5201608 
letterFrequency(bins$bin4, letters="GC", as.prob=T) #0.5206945 
letterFrequency(bins$bin5, letters="GC", as.prob=T) #0.5305203 
letterFrequency(bins$bin6, letters="GC", as.prob=T) #0.5287047 
letterFrequency(bins$bin7, letters="GC", as.prob=T) #0.5225017 
letterFrequency(bins$bin8, letters="GC", as.prob=T) #0.5179812 
letterFrequency(bins$bin9, letters="GC", as.prob=T) #0.5168269 
letterFrequency(bins$bin10, letters="GC", as.prob=T) #0.5206878 
```


``` {r read-CAIG}
caisg <- read.table("CAIS_ofgenes_mouse.txt", header=F, stringsAsFactors=F, sep=",")
names(caisg)

caisg2 <- caisg %>%
  mutate(ENSMUSP = sapply(strsplit(V1, "\\|"), function(x) x[3]))

caig <- read.table("CAI_ofgenes_mouse.txt", header=F, stringsAsFactors=F, sep=",")
names(caig)

caig2 <- caig %>%
  mutate(ENSMUSP = sapply(strsplit(V1, "\\|"), function(x) x[3]))

# Merge the two tables based on the "ENSMUSP" column
mousedf3 <- merge(mousedf2, caisg2[, c("ENSMUSP", "V2", "V3")], by = "ENSMUSP", all.x = TRUE)

names(mousedf3)[4] <- "CAIS"
names(mousedf3)[5] <- "CAIS_unweighted"

mousedf4 <- merge(mousedf3, caig2[, c("ENSMUSP", "V2")], by = "ENSMUSP", all.x = TRUE)

names(mousedf4)[6] <- "CAI"

mousedf4
```


``` {r plotting}
ggplot(mousedf4, aes(x=expr, y=CAIS)) + geom_point(alpha=0.05)
ggplot(mousedf4, aes(x=log10(expr), y=CAIS)) + geom_point(alpha=0.05)
ggplot(mousedf4, aes(x=log10(expr), y=log10(CAIS))) + geom_point(alpha=0.05)

cais4lm <- lm(log10(CAIS) ~ log10(expr), data=subset(mousedf4, log10(expr) > 1.5)) #slope=0.142, R2=0.10
cai4lm <- lm(log10(CAI) ~ log10(expr), data=subset(mousedf4, log10(expr) > 1.5)) #slope=0.0358, R2=0.12

mcais <- ggplot(mousedf4, aes(x=log10(expr), y=log10(CAIS))) + 
  labs( x = "Expression level (ppm)", y = "CAIS of gene") + 
  annotate(geom="text", x=3, y=-1.25, parse=T, label="atop(R^2==0.1, p<2e-16)", color="black", size=6) +
  geom_point(alpha=0.05, stroke=0, size=2) + 
  geom_smooth(color="gray40") +
  geom_segment(aes(x=1.5, 
                 y=(0.141966*1.5)-1.016878, 
                 xend=log10(max(expr)),
                 yend=(0.141966*log10(max(expr)))-1.016878), linewidth=0.5) + 
  scale_x_continuous(labels = label_math(10^.x), breaks = c(-6,-4,-2,0,2,4,6)) +
  scale_y_continuous(labels = label_math(10^.x)) +
  mytheme

mcai <- ggplot(mousedf4, aes(x=log10(expr), y=log10(CAI))) + 
  labs( x = "Expression level (ppm)", y = "CAI of gene") + 
  annotate(geom="text", x=3, y=-0.05, parse=T, label="atop(R^2==0.1, p<2e-16)", color="black", size=6) +
  geom_point(alpha=0.05, stroke=0, size=2) + 
  geom_smooth(color="gray40") + 
  geom_segment(aes(x=1.5, 
                 y=(0.035847*1.5)-0.017775, 
                 xend=log10(max(expr)),
                 yend=(0.035847*log10(max(expr)))-0.017775), linewidth=0.5) + 
  scale_x_continuous(labels = label_math(10^.x), breaks = c(-6,-4,-2,0,2,4,6)) +
  scale_y_continuous(labels = label_math(10^.x)) +
  mytheme

mcais
mcai



names(mousedf4)
dim(mousedf4)
dim(subset(mousedf4, expr>31.6))
2760/18494 #15%
```

``` {r save}
myggsave_gr <- function(x){
  ggsave(plot=x, filename=paste0(deparse(substitute(x)), ".svg"), path="C:/Users/hanon/Documents/Github/aa_flux/CAIS/cais-expr", device="svg", height=4, width=6, units="in")
}

myggsave_gr(mcais)
myggsave_gr(mcai)
```



