---
title: "KJ_figures"
author: "Hanon Mcshea"
date: "7/26/2022"
output: html_document
---

```{r, setup, echo=F, include=F}
knitr::opts_chunk$set(eval=T, warning=F, error=F, message=F)
```

## Set up R and import data

### 0.1 Install the necessary packages and load their libraries

```{r, packages, echo=F, include=F}
library("dplyr")
library("ggplot2")
library("ggtext")
library("lmodel2")
library("wCorr")
library("gridExtra")
library("magrittr")
library("svglite")
library("compositions")
library("scales")

#Set your working directory
setwd("C:/Users/hanon/Documents/GitHub/aa_flux/Figures/")
```

### 0.2 Load data and calculate Kosinski residuals

```{r Data}
#read in amino acid metrics
metrics <- read.delim(file = "Short_amino_acid_properties_Oct23.csv", header=TRUE, stringsAsFactors=FALSE, sep=",") #%>% rename(yps="SlopeAnimal..1496", ops="SlopeAnimal..2101")
metrics

#calculate residuals of fitness effects after accounting for mol volume and disorder propensity
model_resid_LKmarch22 <- lm(metrics$mean_LKmarch22~metrics$Disorder_Propensity + metrics$VolumeA3, weights=(y=(1/(metrics$stderr_LKmarch22))^(2)))
resid_LKmarch22 <- model_resid_LKmarch22$residuals

metrics2 <- cbind(metrics, resid_LKmarch22)

#read in flux data
d <- read.delim(file = "../Parsimony_flux/all_fluxes.csv", header=TRUE, stringsAsFactors=FALSE, sep=",")

ns <- read.delim(file = "../Parsimony_flux/all_NS.csv", header=TRUE, stringsAsFactors=FALSE, sep=",")

dd <- cbind(d, metrics2[,2:141]) %>% mutate(fc_rodent = Glires-Root, fc_primate = Primatomorpha-Root, fc_rp = Glires-Primatomorpha)

dm <- cbind(dd, ns[,5:6])
```

### 0.3 Set up global figure presets

```{r presets}
#settings that affect all or most Figs

#theme
mytheme <- theme(axis.title=element_text(size=16, face="bold"), axis.text=element_text(size=14), panel.background = element_rect(fill = "white", colour = "grey50"), panel.grid.major = element_line(colour = "grey90"), panel.grid.minor = element_blank(), panel.border = element_rect(color = "grey50", fill=NA), plot.margin = unit(c(0.4, 0.4, 0.1, 0.1), "cm"))

#functions for positioning annotations dynamically with axis range
pos_scale <- 0.05

xpos_hi <- function(x){
  xpos = max(x) - pos_scale*diff(range(x))
  return(xpos)}

xpos_lo <- function(x){
  xpos = min(x) + pos_scale*diff(range(x))
  return(xpos)}

ypos_hi <- function(y){
  ypos = max(y) - pos_scale*diff(range(y))
  return(xpos)}

ypos_lo <- function(y){
  ypos = min(y) + pos_scale*diff(range(y))
  return(ypos)}
```

## Figures

###Figure 2
```{r Figure 2}
cor.test(dm$Disorder_Propensity,dm$fc_rp, method='pearson') #R=0.68, p=0.0009
cor.test(dm$Levy_Stickiness,dm$fc_rp, method='pearson') #R=-0.49, p=0.03
cor.test(dm$VolumeA3,dm$fc_rp, method='pearson') #R=-0.72, p=0.0004
cor.test(dm$Polarity,dm$fc_rp, method='pearson') #R=-0.47 p=0.04
cor.test(dm$pGC,dm$fc_rp, method='pearson') #R=0.76, p=1e-04
cor.test(dm$mean_LKmarch22,dm$fc_rp, method='pearson') #R=0.77, p=8e-05
cor.test(dm$resid_LKmarch22,dm$fc_rp, method='pearson') #R=0.23, p=0.3
cor.test(dm$RaifordAerobicCost,dm$fc_rp, method='pearson') #R=-0.70, p=0.0005
cor.test(log10(dm$RaifordAerobicCost),dm$fc_rp, method='pearson') #R=-0.77, p=7e-05
t.test(x=subset(dm, Essential_Costa2015=="Essential")$fc_rp, y=subset(dm, Essential_Costa2015=="Non-essential")$fc_rp, var.equal = T) #p=0.006

cor.test(dm$Mean_RSA,dm$fc_rp, method='pearson') #ns
cor.test(dm$Hydrophobicity,dm$fc_rp, method='pearson') #ns
cor.test(dm$TourasseChangeability,dm$fc_rp, method='pearson') #ns
cor.test(dm$num_Codons,dm$fc_rp, method='pearson') #ns
cor.test(dm$Mean_TdS_conf,dm$fc_rp, method='pearson') #ns
cor.test(dm$Absolute_TS,dm$fc_rp, method='pearson') #ns
cor.test(dm$N1redun,dm$fc_rp, method='pearson') #ns
cor.test(dm$N2redun,dm$fc_rp, method='pearson') #ns
cor.test(dm$N3redun,dm$fc_rp, method='pearson') #ns

cor.test(dm$fc_rp,dm$pGC, method='pearson') #R=0.76, p=1e-04
cor.test(dm$residuals_m2,dm$pGC, method='pearson') #R=0.48, p=0.03
cor.test(dm$kldCAISslope_Proteome,dm$pGC, method='pearson') #R=0.83, p=6e-06
cor.test(dm$Jansen_Gerstein_enrichmentrank,dm$pGC, method='pearson') #R=0.52, p=0.02
cor.test(dm$Cherry_cc,dm$pGC, method='pearson') #R=0.44, p=0.05

Fig2a <- ggplot(dm, aes(x=RaifordAerobicCost, y=fc_rp)) + 
  labs( x = "log(aerobic cost)", y = "Flux difference (ML)") + 
  annotate(geom="text", x=50, y=0.013, parse=T, label="atop(R^2==0.59, p==7e-05)", color="black", size=6) +
  geom_point(size=3) + 
  geom_text(aes(label=aa, color=Essential_Costa2015),hjust=-0.1, vjust=0, size = 6) + 
  scale_color_manual(labels = c("Essential", "Non-Essential"), values = c("red", "blue"), guide="none") + 
  scale_x_log10(
    breaks = c(10, 10^1.5, 100),
    labels = trans_format("log10", math_format(10^.x)))+
  mytheme

Fig2b <- ggplot(dm, aes(x=VolumeA3, y=fc_rp)) + 
  labs( x = "Molecular volume (\u00C5\u00b3)", y = "Flux difference (ML)") + 
  annotate(geom="text", x=210, y=0.012, parse=T, label="atop(R^2==0.51, p==4e-04)", color="black", size=6) +
  geom_point(size=3) + 
  geom_text(aes(label=aa),hjust=-0.1, vjust=0, color="blue", size = 6) + 
  mytheme

Fig2c <- ggplot(dm, aes(x=Disorder_Propensity, y=fc_rp)) + 
  labs( x = "Disorder propensity", y = "Flux difference (ML)") + 
  annotate(geom="text", x=0.15, y=0.012, parse=T, label="atop(R^2==0.47, p==9e-04)", color="black", size=6) +
  geom_point(size=3) + 
  geom_text(aes(label=aa),hjust=-0.1, vjust=0, color="blue", size = 6) + 
  mytheme

Fig2d <- ggplot(dm, aes(x=mean_LKmarch22, y=fc_rp)) + 
  labs( x = "Fitness effect in *E. coli*", y = "Flux difference (ML)") + 
  annotate(geom="text", x=-0.07, y=0.012, parse=T, label="atop(R^2==0.59, p==8e-05)", color="black", size=6) +
  geom_pointrange(aes(xmin=mean_LKmarch22-stderr_LKmarch22, xmax=mean_LKmarch22+stderr_LKmarch22)) +
  geom_point(size=3) + 
  geom_text(aes(label=aa),hjust=-0.1, vjust=0, color="blue", size = 6) + 
  theme(axis.title.x = ggtext::element_markdown()) + 
  mytheme

Fig2e <- ggplot(dm, aes(x=pGC, y=fc_rp)) + 
  labs( x = "%GC", y = "Flux difference (ML)") + 
  annotate(geom="text", x=0.25, y=0.012, parse=T, label="atop(R^2==0.58, p==1e-04)", color="black", size=6) +
  geom_point(size=3) + 
  geom_text(aes(label=aa),hjust=-0.1, vjust=0, color="blue", size = 6) + 
  mytheme

Fig2a
Fig2b
Fig2c
Fig2d
Fig2e
```

### Figure 3
```{r Figure 3}
fitII <- lmodel2(Rnoratio ~ Pnoratio, data=dm, range.y="interval", range.x="interval", nperm=99)
reg <- fitII$regression.results

cor.test(dm$Pnoratio, dm$Pjordan, method='pearson') #R=0.89 p=2e-07
cor.test(dm$Rnoratio, dm$Rjordan, method='pearson') #R=0.92 p=1e-08
cor.test(dm$Pnoratio, dm$Rnoratio, method='pearson') #R=0.54 p=0.01
cor.test(dm$fc_primate, dm$fc_rodent, method='pearson') #R=0.52 p=0.02
cor.test(dm$fc_primate, dm$fc_rodent, method='spearman') #R=0.43 p=0.06

no_serine <- rbind(dm[1:15,], dm[17:20,])
cor.test(no_serine$fc_primate, no_serine$fc_rodent, method='pearson') #R=0.34 p=0.2
cor.test(no_serine$fc_primate, no_serine$fc_rodent, method='spearman') #R=0.34 p=0.2

Fig3a <- ggplot(dm, aes(x=Pnoratio, y=Pjordan)) +
  labs( x = "Primate flux (parsimony; this work)", y = "Primate flux \n(parsimony; Jordan et al.)") + 
  scale_x_continuous(limits=c(-0.4,0.45), breaks=c(-0.4, -0.2, 0, 0.2, 0.4)) + 
  scale_y_continuous(limits=c(-0.4,0.45), breaks=c(-0.4, -0.2, 0, 0.2, 0.4)) + 
  coord_equal() + 
  annotate("rect", xmin = 0, xmax = Inf, ymin = 0, ymax = -Inf, fill= "grey90", alpha=0.5) + 
  annotate("rect", xmin = 0, xmax = -Inf, ymin = Inf, ymax = 0, fill= "grey90", alpha=0.5) + 
  geom_abline(aes(intercept=0, slope=1), color="black") + 
  annotate(geom="text", x=0.25, y=-0.3, parse=T, label="atop(R^2==0.79, p==2e-07)", color="black", size=6) + 
  geom_text(aes(label=aa),hjust=-0.1, vjust=0, color="blue", size = 6) + 
  geom_pointrange(aes(x=Pnoratio, xmin=Pnoratio-Perror, xmax=Pnoratio+Perror)) + 
  geom_point(size=3) + 
  theme(axis.title=element_text(size=16, face="bold"), axis.text=element_text(size=14), panel.background = element_rect(fill = "white", colour = "grey50"), panel.grid.major = element_line(colour = "grey90"), panel.grid.minor = element_blank(), panel.border = element_rect(color = "grey50", fill=NA), plot.margin = unit(c(0.1, 0.1, 0.5, 0.5), "cm"), aspect.ratio = 1)

Fig3b <- ggplot(dm, aes(x=Rnoratio, y=Rjordan)) + 
  labs( x = "Rodent flux (parsimony; this work)", y = "Rodent flux \n(parsimony; Jordan et al.)") + 
  scale_x_continuous(limits=c(-0.4,0.45), breaks=c(-0.4, -0.2, 0, 0.2, 0.4)) + 
  scale_y_continuous(limits=c(-0.4,0.45), breaks=c(-0.4, -0.2, 0, 0.2, 0.4)) + 
  coord_equal() + 
  annotate("rect", xmin = 0, xmax = Inf, ymin = 0, ymax = -Inf, fill= "grey90", alpha=0.5) + 
  annotate("rect", xmin = 0, xmax = -Inf, ymin = Inf, ymax = 0, fill= "grey90", alpha=0.5) + 
  geom_abline(aes(intercept=0, slope=1), color="black") + 
  annotate(geom="text", x=0.25, y=-0.3, parse=T, label="atop(R^2==0.85, p==1e-08)", color="black", size=6) + 
  geom_text(aes(label=aa),hjust=-0.1, vjust=0, color="blue", size = 6) + 
  geom_pointrange(aes(x=Rnoratio, xmin=Rnoratio-Rerror, xmax=Rnoratio+Rerror)) + 
  geom_point(size=3) + 
  theme(axis.title=element_text(size=16, face="bold"), axis.text=element_text(size=14), panel.background = element_rect(fill = "white", colour = "grey50"), panel.grid.major = element_line(colour = "grey90"), panel.grid.minor = element_blank(), panel.border = element_rect(color = "grey50", fill=NA), plot.margin = unit(c(0.1, 0.1, 0.5, 0.5), "cm"), aspect.ratio = 1)

Fig3c <- ggplot(dm, aes(x=Pnoratio, y=Rnoratio))+
  labs( x = "Primate flux (parsimony)", y = "Rodent flux  (parsimony)") + 
  coord_equal() +
  geom_abline(data=subset(reg, Method=="MA"), aes(intercept=Intercept, slope=Slope), color="red", size=1.5) + 
  annotate(geom="text", x=0.2, y=ypos_lo(dm$Rnoratio), parse=T, label="atop(R^2==0.29, p==0.01)", color="black", size=6) + 
  geom_pointrange(aes(xmin=Pnoratio-Perror, xmax=Pnoratio+Perror)) + 
  geom_pointrange(aes(ymin=Rnoratio-Rerror, ymax=Rnoratio+Rerror)) + 
  geom_point(size=3) + 
  geom_text(aes(label=aa),hjust=-0.1, vjust=0, color="blue", size = 6) +
  mytheme

Fig3d <- ggplot(dm, aes(x=fc_primate, y=fc_rodent))+
  labs( x = "Primatomorpha flux (ML)", y = "Glires flux (ML)") + 
  coord_equal() +
  scale_x_continuous(limits=c(-0.015,0.0201), breaks=c(-0.01, 0, 0.01, 0.02)) + 
  scale_y_continuous(limits=c(-0.015,0.0201), breaks=c(-0.01, 0, 0.01, 0.02)) + 
  annotate(geom="text", x=0.015, y=-0.01, parse=T, label="atop(R^2==0.28, p==0.02)", color="black", size=6) + 
  #geom_pointrange(aes(xmin=Pnoratio-Perror, xmax=Pnoratio+Perror)) + 
  #geom_pointrange(aes(ymin=Rnoratio-Rerror, ymax=Rnoratio+Rerror)) + 
  geom_point(size=3) + 
  geom_text(aes(label=aa),hjust=-0.1, vjust=0, color="blue", size = 6) +
  mytheme

Fig3a
Fig3b
Fig3c
Fig3d
```

### Figure 4
```{r Figure 4}
cor.test(dm$projections_m2,dm$Jordan_st1_D, method='pearson') #R=0.789 p=4e-05
cor.test(dm$projections_m2,dm$Jordan_t3_D, method='pearson') #R=0.662 p=0.001
cor.test(dm$residuals_m2,dm$Jordan_st1_D, method='pearson') #R=-0.182 p=0.4
cor.test(dm$projections_m2,dm$TrifonovConsensusOrderOfRecruitment, method='pearson') #R=-0.49 p=0.03

cor.test(dm$Disorder_Propensity,dm$projections_m2, method='spearman') #R=-0.64, p=0.003
cor.test(dm$Disorder_Propensity,dm$projections_m2, method='pearson') #R=-0.71, p=0.0004
weightedCorr(dm$Disorder_Propensity,dm$projections_m2, method='spearman', weights=dm$projection_error) #R=-0.67

cor.test(dm$HC_avg_aafreq,dm$projections_m2, method='pearson') #R=-0.57 p=0.008
cor.test(dm$Levy_Stickiness,dm$projections_m2, method='pearson') #R=0.57 p=0.009
cor.test(dm$Mean_RSA,dm$projections_m2, method='pearson') #R=0.61 p=0.004
cor.test(dm$Polarity,dm$projections_m2, method='pearson') #R=0.56 p=0.01
cor.test(dm$VolumeA3,dm$projections_m2, method='pearson') #ns
cor.test(dm$RaifordAerobicCost,dm$projections_m2, method='pearson') #ns
cor.test(dm$pGC,dm$projections_m2, method='pearson') #ns
cor.test(dm$Hydrophobicity,dm$projections_m2, method='pearson') #ns
cor.test(dm$TourasseChangeability,dm$projections_m2, method='pearson') #ns
cor.test(dm$num_Codons,dm$projections_m2, method='pearson') #ns
cor.test(dm$PAM_sub,dm$projections_m2, method='pearson') #ns
cor.test(dm$BLOSUM_sub,dm$projections_m2, method='pearson') #ns
cor.test(dm$Mean_TdS_conf,dm$projections_m2, method='pearson') #ns
cor.test(dm$Absolute_TS,dm$projections_m2, method='pearson') #ns
cor.test(dm$N1redun,dm$projections_m2, method='pearson') #ns
cor.test(dm$N2redun,dm$projections_m2, method='pearson') #ns
cor.test(dm$N3redun,dm$projections_m2, method='pearson') #ns

cor.test(dm$Disorder_Propensity,dm$Jordan_st1_D, method='pearson') #R=-0.59 p=0.006
cor.test(dm$Levy_Stickiness,dm$Jordan_st1_D, method='pearson') #ns
cor.test(dm$Mean_RSA,dm$Jordan_st1_D, method='pearson') #ns
cor.test(dm$Polarity,dm$Jordan_st1_D, method='pearson') #ns

s_m <- lm(formula=projections_m2 ~ Levy_Stickiness, data=dm) #R2=0.404, p=0.0026
r_m <- lm(formula=projections_m2 ~ Mean_RSA, data=dm) #R2=0.370, p=0.00446
p_m <- lm(formula=projections_m2 ~ Polarity, data=dm) #R2=0.3086, p=0.0110
sr_m <- lm(formula=projections_m2 ~ Levy_Stickiness + Mean_RSA, data=dm) #R2=0.404, p=0.0124
sp_m <- lm(formula=projections_m2 ~ Levy_Stickiness + Polarity, data=dm) #R2=0.413, p=0.0107
rp_m <- lm(formula=projections_m2 ~ Mean_RSA + Polarity, data=dm) #R2=0.372, p=0.0193
srp_m <- lm(formula=projections_m2 ~ Levy_Stickiness + Mean_RSA + Polarity, data=dm) #R2=0.416, p=0.0315
srp_wm <- lm(formula=projections_m2 ~ Levy_Stickiness + Mean_RSA + Polarity, data=dm, weights=(y=(1/projection_error)^(2))) #R2=0.464, p=0.0165

Fig4a<-ggplot(dm, aes(x=Jordan_st1_D, y=projections_m2)) +
  labs( x = "Average flux (Jordan et al.)", y = "Shared flux (parsimony)") +
  scale_y_continuous(limits=c(-0.28,0.28), breaks=c(-0.2, -0.1, 0, 0.1, 0.2)) + 
  annotate(geom="text", x=0.35, y=-0.2, parse=T, label="atop(R^2==0.62, p==4e-05)", color="black", size=6) + 
  geom_pointrange(aes(ymin=projections_m2-projection_error, ymax=projections_m2+projection_error)) +
  geom_pointrange(aes(xmin=Jordan_st1_D-Jordan_st1_Derr, xmax=Jordan_st1_D+Jordan_st1_Derr)) + 
  geom_point(size=3) + 
  geom_text(aes(label=aa),hjust=-0.1, vjust=0, color="blue", size = 6) + 
  mytheme

Fig4b<-ggplot(dm, aes(x=HC_avg_aafreq, y=projections_m2)) +
  labs( x = "Amino acid frequency", y = "Shared flux (parsimony)") +
  #scale_y_continuous(limits=c(-0.28,0.28), breaks=c(-0.2, -0.1, 0, 0.1, 0.2)) + 
  annotate(geom="text", x=0.025, y=-0.2, parse=T, label="atop(R^2==0.32, p==0.009)", color="black", size=6) + 
  geom_pointrange(aes(ymin=projections_m2-projection_error, ymax=projections_m2+projection_error)) +
  geom_point(size=3) + 
  geom_text(aes(label=aa),hjust=-0.1, vjust=0, color="blue", size = 6) + 
  mytheme

Fig4c<-ggplot(dm, aes(x=Disorder_Propensity, y=projections_m2)) +
  labs( x = "Disorder propensity", y = "Shared flux (parsimony)") +
  scale_y_continuous(limits=c(-0.28,0.28), breaks=c(-0.2, -0.1, 0, 0.1, 0.2)) + 
  annotate(geom="text", x=0.125, y=-0.2, parse=T, label="atop(R^2==0.51, p==4e-04)", color="black", size=6) + 
  geom_pointrange(aes(ymin=projections_m2-projection_error, ymax=projections_m2+projection_error)) +
  geom_point(size=3) + 
  geom_text(aes(label=aa),hjust=-0.1, vjust=0, color="blue", size = 6) + 
  mytheme

Fig4a
Fig4b
Fig4c
```

### Figure 5
```{r Figure 5}
cor.test(dm$residuals_m2,dm$kldCAISslope_Proteome, method='pearson') #R=0.71, p=0.0005
cor.test(dm$residuals_m2,dm$fc_rp, method='pearson') #R=0.46, p=0.04
cor.test(dm$fc_rp,dm$kldCAISslope_Proteome, method='pearson') #R=0.58, p=0.007

cor.test(dm$mean_LKmarch22,dm$kldCAISslope_Proteome, method='pearson') #R=0.62, p=0.004
cor.test(dm$VolumeA3,dm$kldCAISslope_Proteome, method='pearson') #ns
cor.test(dm$Disorder_Propensity,dm$kldCAISslope_Proteome, method='pearson') #ns
cor.test(dm$resid_LKmarch22,dm$kldCAISslope_Proteome, method='pearson') #R=0.47, p=0.04

cor.test(dm$num_Codons,dm$kldCAISslope_Proteome, method='pearson') #R=0.51 p=0.02
cor.test(dm$num_Codons,dm$residuals_m2, method='pearson') #R=0.51 p=0.02
cor.test(dm$num_Codons,dm$fc_rp, method='pearson') #ns
cor.test(dm$N3redun,dm$kldCAISslope_Proteome, method='pearson') #R=0.44 p=0.05
cor.test(dm$N3redun,dm$residuals_m2, method='pearson') #R=0.49 p=0.03
cor.test(dm$N3redun,dm$fc_rp, method='pearson') #R=0.50 p=0.02

cor.test(dm$Mean_TdS_conf,dm$kldCAISslope_Proteome, method='pearson') #R=0.48 p=0.03
cor.test(dm$Mean_TdS_conf,dm$residuals_m2, method='pearson') #ns
cor.test(dm$Mean_TdS_conf,dm$fc_rp, method='pearson') #ns


Fig5a<-ggplot(dm, aes(x=residuals_m2, y=kldCAISslope_Proteome)) +
  labs( x = "Flux difference (parsimony)", y = "Preference in vertebrates") +
  geom_segment(aes(x=subset(dm, aa=="K")$residuals_m2, 
                 y=subset(dm, aa=="K")$kldCAISslope_Proteome, 
                 xend=subset(dm, aa=="R")$residuals_m2, 
                 yend=subset(dm, aa=="R")$kldCAISslope_Proteome), color="grey80", alpha=0.3, size=1.5) + 
  geom_segment(aes(x=subset(dm, aa=="I")$residuals_m2, 
                 y=subset(dm, aa=="I")$kldCAISslope_Proteome, 
                 xend=subset(dm, aa=="V")$residuals_m2, 
                 yend=subset(dm, aa=="V")$kldCAISslope_Proteome), color="grey80", alpha=0.3, size=1.5) + 
  annotate(geom="text", x=xpos_hi(dm$residuals_m2), y=ypos_lo(dm$kldCAISslope_Proteome), parse=T, label="atop(R^2==0.50, p==5e-04)", color="black", size=6) +  geom_pointrange(aes(xmin=residuals_m2-residual_error, xmax=residuals_m2+residual_error)) +
  geom_pointrange(aes(ymin=kldCAISslope_Proteome-kldCAISslope_Proteome_Std.Error, ymax=kldCAISslope_Proteome+kldCAISslope_Proteome_Std.Error)) +
  geom_point(size=3) + 
  geom_text(aes(label=aa),hjust=-0.1, vjust=0, color="blue", size = 6) + 
  mytheme

Fig5b<-ggplot(dm, aes(x=fc_rp, y=kldCAISslope_Proteome)) +
  labs( x = "Flux difference (ML)", y = "Preference in vertebrates") +
    geom_segment(aes(x=subset(dm, aa=="K")$fc_rp, 
                 y=subset(dm, aa=="K")$kldCAISslope_Proteome, 
                 xend=subset(dm, aa=="R")$fc_rp, 
                 yend=subset(dm, aa=="R")$kldCAISslope_Proteome), color="grey80", alpha=0.3, size=1.5) + 
  geom_segment(aes(x=subset(dm, aa=="I")$fc_rp, 
                 y=subset(dm, aa=="I")$kldCAISslope_Proteome, 
                 xend=subset(dm, aa=="V")$fc_rp, 
                 yend=subset(dm, aa=="V")$kldCAISslope_Proteome), color="grey80", alpha=0.3, size=1.5) + 
  annotate(geom="text", x=0.012, y=-0.2, parse=T, label="atop(R^2==0.34, p==0.007)", color="black", size=6) +
  geom_pointrange(aes(ymin=kldCAISslope_Proteome-kldCAISslope_Proteome_Std.Error, ymax=kldCAISslope_Proteome+kldCAISslope_Proteome_Std.Error)) +
  geom_point(size=3) + 
  geom_text(aes(label=aa),hjust=-0.1, vjust=0, color="blue", size = 6) + 
  mytheme

Fig5c<-ggplot(dm, aes(x=fc_rp, y=residuals_m2)) +
  labs( x = "Flux difference (ML)", y = "Flux difference (parsimony)") +
  geom_segment(aes(x=subset(dm, aa=="K")$fc_rp, 
                 y=subset(dm, aa=="K")$residuals_m2, 
                 xend=subset(dm, aa=="R")$fc_rp, 
                 yend=subset(dm, aa=="R")$residuals_m2), color="grey80", alpha=0.3, size=1.5) + 
  geom_segment(aes(x=subset(dm, aa=="I")$fc_rp, 
                 y=subset(dm, aa=="I")$residuals_m2, 
                 xend=subset(dm, aa=="V")$fc_rp, 
                 yend=subset(dm, aa=="V")$residuals_m2), color="grey80", alpha=0.3, size=1.5) + 
  annotate(geom="text", x=0.012, y=-0.1, parse=T, label="atop(R^2==0.21, p==0.04)", color="black", size=6) +
  geom_pointrange(aes(ymin=residuals_m2-residual_error, ymax=residuals_m2+residual_error)) +
  geom_point(size=3) + 
  geom_text(aes(label=aa),hjust=-0.1, vjust=0, color="blue", size = 6) + 
  mytheme

Fig5a
Fig5b
Fig5c
```

### Figure 6
```{r Figure 6}
oys <- cor.test(dm$YoungNEW_Estimates,dm$OldNEW_Estimates, method='spearman') #R=0.732, p=0.0004
oyp <- cor.test(dm$YoungNEW_Estimates,dm$OldNEW_Estimates, method='pearson') #R=0.819, p=1e-05

ntts <- cor.test(dm$TransNEW_Estimates,dm$NonTransNEW_Estimates, method='spearman') #R=0.832, p=3e-6
nttp <- cor.test(dm$TransNEW_Estimates,dm$NonTransNEW_Estimates, method='pearson') #R=0.894, p=1e-07


Fig6a<-ggplot(dm, aes(x=OldNEW_Estimates, y=YoungNEW_Estimates)) +
  labs( x = "Preference in\n more-adapted species\n in old Pfams", y = "Preference in\n more-adapted species\n in young Pfams") + 
  annotate("rect", xmin = 0, xmax = Inf, ymin = 0, ymax = -Inf, fill= "grey90", alpha=0.5) + 
  annotate("rect", xmin = 0, xmax = -Inf, ymin = Inf, ymax = 0, fill= "grey90", alpha=0.5) + 
  annotate(geom="text", x=0.025, y=ypos_lo(dm$YoungNEW_Estimates), parse=T, label="atop(R^2==0.67, p==1e-05)", color="black", size=6) +
  geom_pointrange(aes(xmin=OldNEW_Estimates-OldNEW_Std.Error, xmax=OldNEW_Estimates+OldNEW_Std.Error)) +
  geom_pointrange(aes(ymin=YoungNEW_Estimates-YoungNEW_Std.Error, ymax=YoungNEW_Estimates+YoungNEW_Std.Error)) +
  geom_abline(aes(intercept=0, slope=1), color="black") + 
  geom_point(size=3) + 
  geom_text(aes(label=aa),hjust=-0.1, vjust=0, color="blue", size = 6) + 
  theme(axis.title=element_text(size=16, face="bold"), axis.text=element_text(size=14), panel.background = element_rect(fill = "white", colour = "grey50"), panel.grid.major = element_line(colour = "grey90"), panel.grid.minor = element_blank(), panel.border = element_rect(color = "grey50", fill=NA), plot.margin = unit(c(0.1, 0.1, 0.5, 0.5), "cm"), aspect.ratio = 1)
  
Fig6b<-ggplot(dm, aes(x=NonTransNEW_Estimates, y=TransNEW_Estimates)) +
  labs( x = "Preference in\n more-adapted species\n in non-transmembrane Pfams", y = "Preference in\n more-adapted species\n in transmembrane Pfams") + 
  annotate("rect", xmin = 0, xmax = Inf, ymin = 0, ymax = -Inf, fill= "grey90", alpha=0.5) + 
  annotate("rect", xmin = 0, xmax = -Inf, ymin = Inf, ymax = 0, fill= "grey90", alpha=0.5) + 
  annotate(geom="text", x=0.025, y=ypos_lo(dm$TransNEW_Estimates), parse=T, label="atop(R^2==0.80, p==1e-07)", color="black", size=6) +
  geom_pointrange(aes(xmin=NonTransNEW_Estimates-NonTransNEW_Std.Error, xmax=NonTransNEW_Estimates+NonTransNEW_Std.Error)) +
  geom_pointrange(aes(ymin=TransNEW_Estimates-TransNEW_Std.Error, ymax=TransNEW_Estimates+TransNEW_Std.Error)) +
  geom_abline(aes(intercept=0, slope=1), color="black") + 
  geom_point(size=3) + 
  geom_text(aes(label=aa),hjust=-0.1, vjust=0, color="blue", size = 6) + 
  theme(axis.title=element_text(size=16, face="bold"), axis.text=element_text(size=14), panel.background = element_rect(fill = "white", colour = "grey50"), panel.grid.major = element_line(colour = "grey90"), panel.grid.minor = element_blank(), panel.border = element_rect(color = "grey50", fill=NA), plot.margin = unit(c(0.1, 0.1, 0.5, 0.5), "cm"), aspect.ratio = 1)


Fig6a
Fig6b
```

####Signal-to-noise ratios
```{r signal-to-noise}

#calc signal^2:noise^2: signal^2 is variance among point est for the 20 aas. noise^2 is sum of the 20 se^2, can be /20. for CAIS and for D

#pull relevant data
n2_flux <- dm[,c("residuals_m2", "residual_error")]
n2_cais_pfam <- dm[,c("kldCAISslope_Pfam","kldCAISslope_Pfam_Std.Error")]
n2_cais_proteome <- dm[,c("kldCAISslope_Proteome","kldCAISslope_Proteome_Std.Error")]

#calculate error squared
n2_flux2 <- mutate(n2_flux, err_sq = residual_error^2)
n2_cais_pfam2 <- mutate(n2_cais_pfam, err_sq = kldCAISslope_Pfam_Std.Error^2)
n2_cais_proteome2 <- mutate(n2_cais_proteome, err_sq = kldCAISslope_Proteome_Std.Error^2)

#sum of squared errors
sum(n2_flux2$err_sq)/20 #0.0003464315
sum(n2_cais_pfam2$err_sq)/20 #0.0003090742
sum(n2_cais_proteome2$err_sq)/20 #0.0004645876

#calculate variance - this formula already divides by n-1
var(n2_flux2$residuals_m2) #0.005102469
var(n2_cais_pfam2$kldCAISslope_Pfam) #0.006447818
var(n2_cais_proteome2$kldCAISslope_Proteome) #0.01081791

s2n2_flux <- var(n2_flux2$residuals_m2)/(sum(n2_flux2$err_sq)/20) #14.72865
s2n2_cais_pfam <- var(n2_cais_pfam2$kldCAISslope_Pfam)/(sum(n2_cais_pfam2$err_sq)/20) #20.86171
s2n2_cais_proteome <- var(n2_cais_proteome2$kldCAISslope_Proteome)/(sum(n2_cais_proteome2$err_sq)/20) #23.28498

s2n2_cais_proteome/s2n2_cais_pfam #1.116159
s2n2_cais_proteome/s2n2_flux #=1.580931
```

## Supplemental
###S1
```{r supp fig 1}
mrhc <- read.delim(file = "C:/Users/hanon/Documents/Github/aa_flux/Parsimony_flux/Dall.csv", header=TRUE, stringsAsFactors=FALSE, sep=",")
mrhc

mrp <- cor.test(mrhc$mouse_noratio, mrhc$rat_noratio, method='pearson') #R=0.893 p=1e-07
hcp <- cor.test(mrhc$human_noratio, mrhc$chimp_noratio, method='pearson') #R=0.863 p=9e-07

FigS1a <- ggplot(mrhc, aes(x=mouse_noratio, y=rat_noratio))+
  labs( x = "Mouse flux", y = "Rat flux") + 
  scale_x_continuous(limits=c(-0.3,0.3), breaks=c(-0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3)) + 
  scale_y_continuous(limits=c(-0.3,0.3), breaks=c(-0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3)) + 
  coord_equal() + 
  #geom_abline(data=subset(reg, Method=="MA"), aes(intercept=Intercept, slope=Slope), color="red", size=1.5) + 
  annotate(geom="text", x=0.2, y=-0.25, label=paste("R = ", signif(mrp$estimate, digits=3), "\np = ", signif(mrp$p.value, digits=1)), color="black", size=6) + 
  geom_pointrange(aes(xmin=mouse_noratio-mouse_error, xmax=mouse_noratio+mouse_error)) + 
  geom_pointrange(aes(ymin=rat_noratio-rat_error, ymax=rat_noratio+rat_error)) + 
  geom_point(size=3) + 
  geom_abline(aes(intercept=0, slope=1), color="black") + 
  geom_text(aes(label=aa),hjust=-0.1, vjust=0, color="blue", size = 6) +
  mytheme

FigS1b <- ggplot(mrhc, aes(x=human_noratio, y=chimp_noratio))+
  labs( x = "Human flux", y = "Chimp flux") + 
  scale_x_continuous(limits=c(-0.3,0.3), breaks=c(-0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3)) + 
  scale_y_continuous(limits=c(-0.3,0.3), breaks=c(-0.3, -0.2, -0.1, 0, 0.1, 0.2, 0.3)) + 
  coord_equal() + 
  #geom_abline(data=subset(reg, Method=="MA"), aes(intercept=Intercept, slope=Slope), color="red", size=1.5) + 
  annotate(geom="text", x=0.2, y=-0.25, label=paste("R = ", signif(hcp$estimate, digits=3), "\np = ", signif(hcp$p.value, digits=1)), color="black", size=6) + 
  geom_pointrange(aes(xmin=human_noratio-human_error, xmax=human_noratio+human_error)) + 
  geom_pointrange(aes(ymin=chimp_noratio-chimp_error, ymax=chimp_noratio+chimp_error)) + 
  geom_point(size=3) + 
  geom_abline(aes(intercept=0, slope=1), color="black") + 
  geom_text(aes(label=aa),hjust=-0.1, vjust=0, color="blue", size = 6) +
  mytheme

FigS1a
FigS1b
```

###S2
```{r supp fig 2}
pfprp <- cor.test(dm$kldCAISslope_Pfam,dm$kldCAISslope_Proteome, method='pearson') #R=0.960, p=2e-11

FigS2<-ggplot(dm, aes(x=kldCAISslope_Pfam, y=kldCAISslope_Proteome)) +
  labs( x = "Preference in \nmore adapted species \n(pfams only)", y = "Preference in \nmore adapted species \n(whole proteome)") +
    scale_x_continuous(limits=c(-0.2,0.2), breaks=c(-0.2, -0.1, 0, 0.1, 0.2)) + 
  scale_y_continuous(limits=c(-0.2,0.2), breaks=c(-0.2, -0.1, 0, 0.1, 0.2)) + 
  coord_equal() + 
  annotate(geom="text", x=0.12, y=-0.15, label=paste("R = ", signif(pfprp$estimate, digits=3), "\n p = ", signif(pfprp$p.value, digits=1)), color="black", size=6) +
  geom_pointrange(aes(xmin=kldCAISslope_Pfam-kldCAISslope_Pfam_Std.Error, xmax=kldCAISslope_Pfam+kldCAISslope_Pfam_Std.Error)) +
  geom_pointrange(aes(ymin=kldCAISslope_Proteome-kldCAISslope_Proteome_Std.Error, ymax=kldCAISslope_Proteome+kldCAISslope_Proteome_Std.Error)) +
  geom_point(size=3) + 
  #geom_abline(aes(intercept=0, slope=1), color="black") + 
  geom_text(aes(label=aa),hjust=-0.1, vjust=0, color="blue", size = 6) + 
  mytheme
  
FigS2
```


## Export the figures
```{r save}
#Set your own paths!
myggsave_sq <- function(x){
  ggsave(plot=x, filename=paste0(deparse(substitute(x)), ".svg"), path="C:/Users/hanon/Documents/Github/aa_flux/Figures", device="svg", height=5, width=5, units="in")
}

myggsave_u <- function(x){
  ggsave(plot=x, filename=paste0(deparse(substitute(x)), ".svg"), path="C:/Users/hanon/Documents/Github/aa_flux/Figures", device="svg", height=5, width=4.5, units="in")
}

myggsave_m <- function(x){
  ggsave(plot=x, filename=paste0(deparse(substitute(x)), ".svg"), path="C:/Users/hanon/Documents/Github/aa_flux/Figures", device="svg", height=5, width=7, units="in")
}

myggsave_ms <- function(x){
  ggsave(plot=x, filename=paste0(deparse(substitute(x)), ".svg"), path="C:/Users/hanon/Documents/Github/aa_flux/Figures", device="svg", height=4.5, width=5, units="in")
}

#was 3.5x3.5 and 3.5x5 and 5x6

myggsave_gr <- function(x){
  ggsave(plot=x, filename=paste0(deparse(substitute(x)), ".svg"), path="C:/Users/hanon/Documents/Github/aa_flux/Figures", device="svg", height=5, width=8.09, units="in")
}

myggsave_sm <- function(x){
  ggsave(plot=x, filename=paste0(deparse(substitute(x)), ".svg"), path="C:/Users/hanon/Documents/Github/aa_flux/Figures", device="svg", height=3, width=4.04, units="in")
}

#2
myggsave_ms(Fig2a)
myggsave_ms(Fig2b)
myggsave_ms(Fig2c)
myggsave_ms(Fig2d)
myggsave_ms(Fig2e)

#3
myggsave_sq(Fig3a)
myggsave_sq(Fig3b)
myggsave_m(Fig3c)
myggsave_sq(Fig3d)

#4
myggsave_ms(Fig4a)
myggsave_ms(Fig4b)
myggsave_ms(Fig4c)

#5
myggsave_u(Fig5a)
myggsave_u(Fig5b)
myggsave_u(Fig5c)

myggsave_sq(Fig6a)
myggsave_sq(Fig6b)

myggsave_sq(FigS1a)
myggsave_sq(FigS1b)
myggsave_m(FigS2)
```
